package it.univr.dndlang;

import it.univr.dndlang.DnDLangParser.AddSubExprContext;
import it.univr.dndlang.DnDLangParser.AndExprContext;
import it.univr.dndlang.DnDLangParser.BoolExprContext;
import it.univr.dndlang.DnDLangParser.BreakStmtContext;
import it.univr.dndlang.DnDLangParser.DiceAdvDisExprContext;
import it.univr.dndlang.DnDLangParser.DiceOnlyContext;
import it.univr.dndlang.DnDLangParser.EqualityExprContext;
import it.univr.dndlang.DnDLangParser.ExprStmtContext;
import it.univr.dndlang.DnDLangParser.FloatExprContext;
import it.univr.dndlang.DnDLangParser.IdExprContext;
import it.univr.dndlang.DnDLangParser.IfStmtContext;
import it.univr.dndlang.DnDLangParser.IntExprContext;
import it.univr.dndlang.DnDLangParser.MulDivExprContext;
import it.univr.dndlang.DnDLangParser.OrExprContext;
import it.univr.dndlang.DnDLangParser.ParenExprContext;
import it.univr.dndlang.DnDLangParser.PreIncExprContext;
import it.univr.dndlang.DnDLangParser.RelationalExprContext;
import it.univr.dndlang.DnDLangParser.SaveVsExprContext;
import it.univr.dndlang.DnDLangParser.StringExprContext;
import it.univr.dndlang.DnDLangParser.SwitchStmtContext;
import it.univr.dndlang.DnDLangParser.TernaryExprContext;
import it.univr.dndlang.DnDLangParser.UnaryExprContext;
import it.univr.dndlang.DnDLangParser.WhileStmtContext;
import org.antlr.v4.runtime.ParserRuleContext;

/*
 * DESIGN
 * ------
 *
 * This class implements the core Interpreter for the DnDLang using the 
 * Visitor pattern. The AST generated by ANTLR is traversed node by node.
 * 
 * State management during traversal:
 * - Environment: A scoped symbol table handles variable and function declarations.
 * - Struct Prefixes: To support the 'hero.' and 'foe.' syntactic sugar in 
 *   their respective sections, we maintain a `currentStructPrefix`. 
 * - Control Flow: A `isBreaking` boolean flag is used to propagate 'break' 
 *   statements up the AST tree without using exceptions.
 * - Returns: A `currentReturnType` keeps track of the return type of the 
 *   currently executing function, allowing type coercion and validation 
 *   upon returning.
 */

/** 
 * AST Visitor that interprets the AST generated by the DnDLang parser. 
 */
public class DnDInterpreter extends DnDLangBaseVisitor<Object> {
  /* Symbol table environment for managing scopes. */
  private final Environment env = new Environment();
  /* Active prefix for hero./foe. sections. */
  private String currentStructPrefix = "";
  /* Flag to indicate an active 'break' statement. */
  private boolean isBreaking = false;
  /* Expected return type of the currently executing function. */
  private String currentReturnType = "Void";

  /* --- Program Structure (program, hero, foe, quest) --- */

  /** 
   * Visits the root program node. 
   */
  @Override
  public Object visitProgram(DnDLangParser.ProgramContext ctx) {
    /* Safety early return if the AST is empty */
    if (ctx.children == null) return null;

    int heroCount = 0;
    int foeCount = 0;

    for (var child : ctx.children) {

      if (child instanceof DnDLangParser.HeroSectionContext heroCtx) {
        if (++heroCount > 1) {
          throw new DnDLangError("Duplicate 'hero' section.", heroCtx.getStart().getLine());
        }
        visit(heroCtx);
      } else if (child instanceof DnDLangParser.FoeSectionContext foeCtx) {
        if (++foeCount > 1) {
          throw new DnDLangError("Duplicate 'foe' section.", foeCtx.getStart().getLine());
        }
        visit(foeCtx);
      } else if (child instanceof DnDLangParser.FunctionDeclContext funcCtx) {
        String funcName = funcCtx.ID().getText();
        String returnType = funcCtx.getChild(1).getText();
        env.declareFunction(funcName, returnType, funcCtx);

      } else if (child instanceof DnDLangParser.QuestSectionContext questCtx) {
        visit(questCtx);
      }
    }

    return null;
  }

  /** 
   * Sets the "hero." prefix and executes the hero section declarations. 
   */
  @Override
  public Object visitHeroSection(DnDLangParser.HeroSectionContext ctx) {
    currentStructPrefix = "hero.";
    visitDeclarativeBlock(ctx.block());
    currentStructPrefix = "";
    return null;
  }

  /** 
   * Sets the "foe." prefix and executes the foe section declarations. 
   */
  @Override
  public Object visitFoeSection(DnDLangParser.FoeSectionContext ctx) {
    currentStructPrefix = "foe.";
    visitDeclarativeBlock(ctx.block());
    currentStructPrefix = "";
    return null;
  }

  /** 
   * Executes the quest section block, which serves as the main entry point. 
   */
  @Override
  public Object visitQuestSection(DnDLangParser.QuestSectionContext ctx) {
    return visit(ctx.block());
  }

  /* --- Blocks and Statements --- */

  /** 
   * Opens a new scope, executes all statements within the block, and closes the scope. 
   */
  @Override
  public Object visitBlock(DnDLangParser.BlockContext ctx) {
    env.enterBlock();
    if (ctx.statement() != null) {
      for (var stmt : ctx.statement()) {
        visit(stmt);
        /* If a break is active, immediately interrupt block execution. */
        if (isBreaking) {
          break;
        }
      }
    }
    env.exitBlock();
    return null;
  }

  /**
   * Declares a variable by determining its type, evaluating the expression, 
   * and registering it in the environment.
   */
  @Override
  public Object visitDecl(DnDLangParser.DeclContext ctx) {
    String declaredType;
    if (ctx.TYPE_HP() != null) declaredType = "HP";
    else if (ctx.TYPE_AC() != null) declaredType = "AC";
    else if (ctx.TYPE_GOLD() != null) declaredType = "Gold";
    else if (ctx.TYPE_INT() != null) declaredType = "Int";
    else if (ctx.TYPE_FLOAT() != null) declaredType = "Float";
    else if (ctx.TYPE_BOOL() != null) declaredType = "Bool";
    else if (ctx.TYPE_STRING() != null) declaredType = "String";
    else throw new DnDLangError("Unknown type", ctx.getStart().getLine());

    String rawId = ctx.ID().getText();
    /* Prefix "hero." or "foe." if we are inside a struct section. */
    String id = currentStructPrefix + rawId;

    Object value;

    if (ctx.expr() != null) {

      value = visit(ctx.expr());

    } else {
      value = getDefaultValueForType(declaredType, ctx);
    }

    value = coerceToDeclaredType(value, declaredType);
    env.declare(id, value, declaredType);
    return null;
  }

  /* --- Assignments and increments/decrements --- */

  /** 
   * Handles simple and compound assignments (=, +=, -=, *=, /=). 
   */
  @Override
  public Object visitAssign(DnDLangParser.AssignContext ctx) {
    String rawId = ctx.ID().getText();
    String id = resolveId(rawId, ctx.getStart().getLine());

    if (!env.contains(id)) {
      throw new DnDLangError(
          "Cannot assign, undeclared variable '" + id + "'", ctx.getStart().getLine());
    }
    String declaredType = env.getType(id);
    Object rightValue;

    rightValue = visit(ctx.expr());

    Object leftValue = null;
    Object finalValue = null;

    /* The second child of the AST node is the assignment operator */
    switch (ctx.getChild(1).getText()) {
      case "=":
        finalValue = rightValue;
        break;

      case "+=":
        leftValue = env.lookup(id);
        double sum = asDouble(leftValue, ctx) + asDouble(rightValue, ctx);
        /* Preserve integer type only if both operands are integers */
        finalValue = areBothIntegers(leftValue, rightValue) ? (int) sum : sum;
        break;

      case "-=":
        leftValue = env.lookup(id);
        double diff = asDouble(leftValue, ctx) - asDouble(rightValue, ctx);
        finalValue = areBothIntegers(leftValue, rightValue) ? (int) diff : diff;
        break;

      case "*=":
        leftValue = env.lookup(id);
        double prod = asDouble(leftValue, ctx) * asDouble(rightValue, ctx);
        finalValue = areBothIntegers(leftValue, rightValue) ? (int) prod : prod;
        break;

      case "/=":
        leftValue = env.lookup(id);
        double divRight = asDouble(rightValue, ctx);
        if (divRight == 0) {
          throw new DnDLangError("Division by zero", ctx.getStart().getLine());
        }
        double quot = asDouble(leftValue, ctx) / divRight;
        finalValue = areBothIntegers(leftValue, rightValue) ? (int) quot : quot;
        break;

      default:
        throw new DnDLangError(
            "Runtime error: Unrecognized assignment operator", ctx.getStart().getLine());
    }
    /* Coerce the result to the declared type before storing it */
    finalValue = coerceToDeclaredType(finalValue, declaredType);
    env.assign(id, finalValue);

    return null;
  }

  /** 
   * Evaluates post-increment/decrement (x++, x--) and returns the previous value. 
   */
  @Override
  public Object visitPostIncExpr(DnDLangParser.PostIncExprContext ctx) {
    String rawId = ctx.ID().getText();
    String id = resolveId(rawId, ctx.getStart().getLine());
    String declaredType = env.getType(id);

    Object oldValue = env.lookup(id);

    double calcValue = asDouble(oldValue, ctx);
    if (ctx.PLUS_PLUS() != null) {
      calcValue += 1.0;
    } else if (ctx.MINUS_MINUS() != null) {
      calcValue -= 1.0;
    } else {
      throw new DnDLangError(
          "Runtime error: Unrecognized increment operator", ctx.getStart().getLine());
    }

    /* Retain original type (Integer or Double) */
    Object newValue = (oldValue instanceof Integer) ? (int) calcValue : calcValue;

    newValue = coerceToDeclaredType(newValue, declaredType);
    env.assign(id, newValue);

    /* Post-increment: returns the value prior to modification */
    return oldValue;
  }

  /** 
   * Evaluates pre-increment/decrement (++x, --x) and returns the new value. 
   */
  @Override
  public Object visitPreIncExpr(PreIncExprContext ctx) {
    String rawId = ctx.ID().getText();
    String id = resolveId(rawId, ctx.getStart().getLine());
    String declaredType = env.getType(id);

    Object oldValue = env.lookup(id);

    double calcValue = asDouble(oldValue, ctx);
    if (ctx.PLUS_PLUS() != null) {
      calcValue += 1.0;
    } else if (ctx.MINUS_MINUS() != null) {
      calcValue -= 1.0;
    } else {
      throw new DnDLangError(
          "Runtime error: Unrecognized increment operator", ctx.getStart().getLine());
    }

    Object newValue = (oldValue instanceof Integer) ? (int) calcValue : calcValue;

    newValue = coerceToDeclaredType(newValue, declaredType);
    env.assign(id, newValue);

    return newValue;
  }

  /** 
   * Evaluates the ternary operator: condition ? true_value : false_value. 
   */
  @Override
  public Object visitTernaryExpr(TernaryExprContext ctx) {
    Object condition = visit(ctx.expr(0));
    if (!(condition instanceof Boolean)) {
      throw new DnDLangError(
          "The condition of the ternary operator must be a boolean",
          ctx.getStart().getLine());
    }

    if ((Boolean) condition) {
      return visit(ctx.expr(1));

    } else {
      return visit(ctx.expr(2));
    }
  }

  /* --- Print and String interpolation --- */

  /** 
   * Prints the value of an expression or an interpolated string. 
   */
  @Override
  public Object visitPrintStmt(DnDLangParser.PrintStmtContext ctx) {
    Object value = visit(ctx.expr() != null ? ctx.expr() : ctx.ISTRING());
    System.out.println(value);
    return null;
  }

  /* --- Literals --- */

  /** 
   * Returns the integer value of the literal. 
   */
  @Override
  public Object visitIntExpr(IntExprContext ctx) {
    return Integer.parseInt(ctx.INT().getText());
  }

  /** 
   * Returns the decimal value of the literal. 
   */
  @Override
  public Object visitFloatExpr(FloatExprContext ctx) {
    return Double.parseDouble(ctx.FLOAT().getText());
  }

  /** 
   * Returns the boolean value of the literal. 
   */
  @Override
  public Object visitBoolExpr(BoolExprContext ctx) {
    return Boolean.parseBoolean(ctx.BOOL().getText());
  }

  /** 
   * Returns the string content, managing escape sequences. 
   */
  @Override
  public Object visitStringExpr(StringExprContext ctx) {
    String str = ctx.STRING().getText();
    String content = str.substring(1, str.length() - 1);

    return content.replace("\\n", "\n").replace("\\t", "\t").replace("\\\"", "\"");
  }

  /** 
   * Interpolates an i"..." string, replacing ${expr} with the evaluated value. 
   */
  @Override
  public Object visitIStringExpr(DnDLangParser.IStringExprContext ctx) {
    String rawString = ctx.ISTRING().getText();
    /* Remove the i" prefix and the trailing quotes */
    String content = rawString.substring(2, rawString.length() - 1);
    content = content.replace("\\n", "\n").replace("\\t", "\t").replace("\\\"", "\"");

    /* Find all occurrences of ${...} in the string */
    java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("\\$\\{([^}]+)\\}");
    java.util.regex.Matcher matcher = pattern.matcher(content);
    StringBuilder result = new StringBuilder();

    while (matcher.find()) {
      String exprText = matcher.group(1).trim();
      String replacement;

      try {
        /* Create a mini-parser to evaluate the expression inside ${...} */
        org.antlr.v4.runtime.CharStream input =
            org.antlr.v4.runtime.CharStreams.fromString(exprText);
        DnDLangLexer lexer = new DnDLangLexer(input);
        org.antlr.v4.runtime.CommonTokenStream tokens =
            new org.antlr.v4.runtime.CommonTokenStream(lexer);
        DnDLangParser parser = new DnDLangParser(tokens);

        parser.removeErrorListeners();

        DnDLangParser.ExprContext exprCtx = parser.expr();

        if (parser.getNumberOfSyntaxErrors() > 0) {
          replacement = "[SYNTAX ERROR IN: " + exprText + "]";
        } else {
          Object val = visit(exprCtx);

          /* 
           * Search for the variable to determine if a type suffix 
           * should be appended (e.g. HP, AC, gp). 
           */
          String resolvedIdForType = null;
          if (!currentStructPrefix.isEmpty() && env.contains(currentStructPrefix + exprText)) {
            resolvedIdForType = currentStructPrefix + exprText;
          } else if (env.contains(exprText)) {
            resolvedIdForType = exprText;
          }

          if (resolvedIdForType != null) {
            String type = env.getType(resolvedIdForType);
            replacement =
                switch (type) {
                  case "HP" -> val + " HP";
                  case "AC" -> val + " AC";
                  case "Gold" -> val + " gp";
                  default -> val.toString();
                };
          } else {
            replacement = val.toString();
          }
        }
      } catch (Exception e) {
        replacement = "[RUNTIME ERROR: " + exprText + "]";
      }

      matcher.appendReplacement(result, java.util.regex.Matcher.quoteReplacement(replacement));
    }
    matcher.appendTail(result);

    return result.toString();
  }

  /* --- D&D Mechanics and Dice (d20, adv/dis, save/vs) --- */

  @Override
  public Object visitD20Expr(DnDLangParser.D20ExprContext ctx) {
    return rollDice(20);
  }

  @Override
  public Object visitD12Expr(DnDLangParser.D12ExprContext ctx) {
    return rollDice(12);
  }

  @Override
  public Object visitD10Expr(DnDLangParser.D10ExprContext ctx) {
    return rollDice(10);
  }

  @Override
  public Object visitD8Expr(DnDLangParser.D8ExprContext ctx) {
    return rollDice(8);
  }

  @Override
  public Object visitD6Expr(DnDLangParser.D6ExprContext ctx) {
    return rollDice(6);
  }

  @Override
  public Object visitD4Expr(DnDLangParser.D4ExprContext ctx) {
    return rollDice(4);
  }

  @Override
  public Object visitD3Expr(DnDLangParser.D3ExprContext ctx) {
    return rollDice(3);
  }

  /** 
   * Rolls two dice and keeps the highest (advantage) or lowest (disadvantage). 
   */
  @Override
  public Object visitDiceAdvDisExpr(DiceAdvDisExprContext ctx) {
    /* 
     * TEACHER: 
     * In Dungeons & Dragons, "Advantage" and "Disadvantage" are mechanics 
     * where you roll a die twice and take the higher or lower result, 
     * respectively. This represents favorable or unfavorable conditions.
     */
    int r1 = (int) visit(ctx.diceOnly());
    int r2 = (int) visit(ctx.diceOnly());

    boolean isAdv = ctx.ADV() != null;

    int res = isAdv ? Math.max(r1, r2) : Math.min(r1, r2);

    String type = isAdv ? "Advantage" : "Disadvantage";
    System.out.println(" > [" + type + "] Rolled " + r1 + " and " + r2 + " -> Keeping " + res);

    return res;
  }

  /** 
   * Evaluates a saving throw (save) or opposed check (vs) and returns a boolean. 
   */
  @Override
  public Object visitSaveVsExpr(SaveVsExprContext ctx) {
    /*
     * TEACHER:
     * A Saving Throw (SAVE) compares a rolled value against a static target 
     * number known as the Difficulty Class (DC). Meeting or exceeding the DC 
     * results in a success.
     * An Opposed Check (VS) compares a rolled value against an opponent's 
     * rolled value. The higher result wins.
     */
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));
    double l = asDouble(left, ctx);
    double r = asDouble(right, ctx);

    boolean success;

    if (ctx.SAVE() != null) {
      success = l >= r;
      System.out.println(
          "  > [ Saving Throw ] Total: "
              + (int) l
              + " vs DC: "
              + (int) r
              + " -> "
              + (success ? "SUCCESS" : "FAILURE"));
      return success;
    } else if (ctx.VS() != null) {
      success = l > r;
      System.out.println(
          "  > [ Opposed Check ] Active: "
              + (int) l
              + " vs Opponent: "
              + (int) r
              + " -> "
              + (success ? "VICTORY" : "DEFEAT"));
      return success;
    } else {
      throw new DnDLangError("", ctx.getStart().getLine());
    }
  }

  /* --- Arithmetic, Relational, and Logical Expressions --- */

  /** 
   * Returns the value of a variable, resolving the struct prefix if necessary. 
   */
  @Override
  public Object visitIdExpr(IdExprContext ctx) {
    String rawId = ctx.ID().getText();
    String id = resolveId(rawId, ctx.getStart().getLine());
    return env.lookup(id);
  }

  /** 
   * Evaluates the expression within parentheses. 
   */
  @Override
  public Object visitParenExpr(ParenExprContext ctx) {
    return visit(ctx.expr());
  }

  /** 
   * Evaluates addition or subtraction, preserving the integer type if possible. 
   */
  @Override
  public Object visitAddSubExpr(AddSubExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    double l = asDouble(left, ctx);
    double r = asDouble(right, ctx);
    double result = 0;

    if (ctx.PLUS() != null) {
      result = l + r;
    } else if (ctx.MINUS() != null) {
      result = l - r;
    }

    if (areBothIntegers(left, right)) {
      return (int) result;
    }
    return result;
  }
  /** 
   * Evaluates multiplication, division, or modulo with division by zero prevention. 
   */
  @Override
  public Object visitMulDivExpr(MulDivExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    double l = asDouble(left, ctx);
    double r = asDouble(right, ctx);
    double result = 0;

    if (ctx.STAR() != null) {
      result = l * r;
    } else if (ctx.SLASH() != null) {
      if (r == 0) throw new DnDLangError("Division by zero", ctx.getStart().getLine());
      result = l / r;
    } else if (ctx.PERCENT() != null) {
      if (r == 0) throw new DnDLangError("Modulo by zero", ctx.getStart().getLine());
      result = l % r;
    }

    if (areBothIntegers(left, right)) {
      return (int) result;
    }
    return result;
  }

  /** 
   * Evaluates a relational comparison (<, <=, >, >=). 
   */
  @Override
  public Object visitRelationalExpr(RelationalExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    double l = asDouble(left, ctx);
    double r = asDouble(right, ctx);

    if (ctx.LT() != null) return l < r;
    else if (ctx.LE() != null) return l <= r;
    else if (ctx.GT() != null) return l > r;
    else if (ctx.GE() != null) return l >= r;

    throw new DnDLangError("Unrecognized relational operator", ctx.getStart().getLine());
  }

  /** 
   * Evaluates equality (==) or inequality (!=). 
   */
  @Override
  public Object visitEqualityExpr(EqualityExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    boolean isEqual;

    if (left instanceof Number && right instanceof Number) {
      isEqual = asDouble(left, ctx) == asDouble(right, ctx);
    } else {
      isEqual = left.equals(right);
    }

    if (ctx.EQ() != null) return isEqual;
    else if (ctx.NEQ() != null) return !isEqual;

    throw new DnDLangError("Unrecognized comparison operator", ctx.getStart().getLine());
  }

  /* --- Function Calls --- */

  /** 
   * Invokes a function: evaluates arguments, opens a local scope, and handles the return. 
   */
  @Override
  public Object visitFunctionCallExpr(DnDLangParser.FunctionCallExprContext ctx) {
    String funcName = ctx.ID().getText();
    int line = ctx.getStart().getLine();

    /* Retrieve the symbol and the AST node of the original declaration */
    FunctionSymbol function = env.lookupFunction(funcName, line);
    DnDLangParser.FunctionDeclContext delCtx = function.getDeclarationNode();

    /* Evaluate all caller arguments before entering the function's scope */
    java.util.ArrayList<Object> evalArguments = new java.util.ArrayList<>();
    if (ctx.expr() != null) {
      for (DnDLangParser.ExprContext argCtx : ctx.expr()) {
        evalArguments.add(visit(argCtx));
      }
    }

    /* Retrieve formal parameters */
    DnDLangParser.ParamListContext paramListCtx = delCtx.paramList();
    java.util.List<DnDLangParser.ParamDeclContext> formalParameter = new java.util.ArrayList<>();
    if (paramListCtx != null) {
      formalParameter = paramListCtx.paramDecl();
    }

    /* Check arity */
    if (evalArguments.size() != formalParameter.size()) {
      throw new DnDLangError(
          "Error: function '"
              + funcName
              + "' expects "
              + formalParameter.size()
              + " parameters, but "
              + evalArguments.size()
              + " were provided.",
          line);
    }

    /* Save and update the return type to support recursive/nested calls */
    String previousReturnType = currentReturnType;
    currentReturnType = function.getType();

    env.enterBlock();

    /* 
     * WHY: 
     * The return statement is implemented by throwing a ReturnException. 
     * We catch it here to cleanly exit the nested visitor functions and 
     * retrieve the returned value, simulating the unwinding of a call stack.
     */
    try {

      /* Declare parameters in the local scope; error out if types clash */
      for (int i = 0; i < formalParameter.size(); i++) {
        DnDLangParser.ParamDeclContext paramCtx = formalParameter.get(i);
        String paramType = paramCtx.getChild(0).getText();
        String paramName = paramCtx.ID().getText();

        Object argValue = evalArguments.get(i);
        Object coercedValue;

        try {
          coercedValue = coerceToDeclaredType(argValue, paramType);
        } catch (Exception e) {
          throw new DnDLangError(
              "Type mismatch for parameter '"
                  + paramName
                  + "'. "
                  + "Expected: "
                  + paramType
                  + ", Received: incompatible value.",
              line);
        }

        env.declare(paramName, coercedValue, paramType);
      }

      /* Execute function body; a return statement will throw a ReturnException */
      visit(delCtx.block());

      /* If we reach here without a ReturnException, a non-Void function is missing a return */
      if (!"Void".equals(currentReturnType)) {
        throw new DnDLangError(
            "Function '"
                + funcName
                + "' must return a value of type "
                + currentReturnType
                + " but lacks a return statement.",
            line);
      }
      return null;

    } catch (ReturnException e) {
      /* Return statement was executed: extract the value from the exception */
      Object retVal = e.getValue();

      if ("Void".equals(currentReturnType)) {
        if (retVal != null) {
          throw new DnDLangError(
              "Function '" + funcName + "' is Void and cannot return a value.", line);
        }
        return null;
      }

      try {
        return coerceToDeclaredType(retVal, currentReturnType);
      } catch (IllegalArgumentException ex) {
        throw new DnDLangError(
            "Function '"
                + funcName
                + "' must return "
                + currentReturnType
                + " but returned an incompatible type.",
            line);
      }

    } finally {
      /* Restore the scope and the caller's return type */
      env.exitBlock();
      currentReturnType = previousReturnType;
    }
  }

  /** 
   * Evaluates an expression used as a statement (discards the result). 
   */
  @Override
  public Object visitExprStmt(ExprStmtContext ctx) {
    visit(ctx.expr());
    return null;
  }

  /** 
   * Rolls the die specified by the diceOnly rule. 
   */
  @Override
  public Object visitDiceOnly(DiceOnlyContext ctx) {
    if (ctx.D20() != null) return rollDice(20);
    if (ctx.D12() != null) return rollDice(12);
    if (ctx.D10() != null) return rollDice(10);
    if (ctx.D8() != null) return rollDice(8);
    if (ctx.D6() != null) return rollDice(6);
    if (ctx.D4() != null) return rollDice(4);
    if (ctx.D3() != null) return rollDice(3);
    throw new DnDLangError("Unrecognized die", ctx.getStart().getLine());
  }

  /** 
   * Evaluates logical AND between two boolean expressions. 
   */
  @Override
  public Object visitAndExpr(AndExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    if (!(left instanceof Boolean) || !(right instanceof Boolean)) {
      throw new DnDLangError(
          "The '&&' operator requires two boolean values", ctx.getStart().getLine());
    }
    return (Boolean) left && (Boolean) right;
  }

  /** 
   * Evaluates logical OR between two boolean expressions. 
   */
  @Override
  public Object visitOrExpr(OrExprContext ctx) {
    Object left = visit(ctx.expr(0));
    Object right = visit(ctx.expr(1));

    if (!(left instanceof Boolean) || !(right instanceof Boolean)) {
      throw new DnDLangError(
          "The '||' operator requires two boolean values", ctx.getStart().getLine());
    }
    return (Boolean) left || (Boolean) right;
  }

  /** 
   * Evaluates a unary operator: logical NOT (!) or arithmetic negation (-). 
   */
  @Override
  public Object visitUnaryExpr(UnaryExprContext ctx) {
    Object value = visit(ctx.expr());

    if (ctx.NOT() != null) {
      if (!(value instanceof Boolean)) {
        throw new DnDLangError(
            "The '!' operator requires a boolean value", ctx.getStart().getLine());
      }
      return !(Boolean) value;
    } else if (ctx.MINUS() != null) {
      double num = asDouble(value, ctx);
      if (value instanceof Integer) {
        return (int) -num;
      }
      return -num;
    }
    throw new DnDLangError("Unrecognized unary operator", ctx.getStart().getLine());
  }

  /* --- Returns and Function Declarations --- */

  /** 
   * Throws a ReturnException to halt execution and return a value. 
   */
  @Override
  public Object visitReturnStmt(DnDLangParser.ReturnStmtContext ctx) {
    Object value = (ctx.expr() != null) ? visit(ctx.expr()) : null;
    throw new ReturnException(value, currentReturnType);
  }

  /** 
   * Registers a function in the environment with its name, return type, and AST node. 
   */
  @Override
  public Object visitFunctionDecl(DnDLangParser.FunctionDeclContext ctx) {
    String name = ctx.ID().getText();

    String returnType = ctx.getChild(1).getText();

    env.declareFunction(name, returnType, ctx);
    return null;
  }

  /* --- Control Flow (if, while, switch, break) --- */

  /** 
   * Evaluates the condition and executes either the then-block or the else-block. 
   */
  @Override
  public Object visitIfStmt(IfStmtContext ctx) {
    Object condition = visit(ctx.expr());

    if (!(condition instanceof Boolean)) {
      throw new DnDLangError(
          "The condition of the 'if' construct must be a boolean", ctx.getStart().getLine());
    }
    if ((Boolean) condition) {
      visit(ctx.block(0));
    } else if (ctx.block().size() > 1) {
      visit(ctx.block(1));
    }
    return null;
  }

  /** 
   * Executes the loop body until the condition is false or a break is encountered. 
   */
  @Override
  public Object visitWhileStmt(WhileStmtContext ctx) {
    while (true) {
      Object condition = visit(ctx.expr());

      if (!(condition instanceof Boolean)) {
        throw new DnDLangError(
            "The condition of the 'while' construct must be a boolean",
            ctx.getStart().getLine());
      }

      if (!(Boolean) condition) {
        break;
      }

      visit(ctx.block());

      if (isBreaking) {
        isBreaking = false;
        break;
      }
    }
    return null;
  }

  /** 
   * Matches the switch value with each case and executes the corresponding block. 
   */
  @Override
  public Object visitSwitchStmt(SwitchStmtContext ctx) {
    Object switchValue = visit(ctx.expr());

    for (DnDLangParser.CaseBlockContext caseCtx : ctx.caseBlock()) {
      Object caseValue = visit(caseCtx.expr());
      boolean isMatch = false;

      if (switchValue instanceof Number && caseValue instanceof Number) {
        isMatch = asDouble(switchValue, ctx) == asDouble(caseValue, ctx);
      } else {
        isMatch = switchValue.equals(caseValue);
      }

      if (isMatch) {
        visit(caseCtx.block());
        /* Reset the break flag after executing the corresponding case */
        isBreaking = false;
        return null;
      }
    }
    if (ctx.defaultBlock() != null) {
      visit(ctx.defaultBlock().block());
      isBreaking = false;
    }
    return null;
  }

  /** 
   * Activates the break flag to interrupt the current loop. 
   */
  @Override
  public Object visitBreakStmt(BreakStmtContext ctx) {
    isBreaking = true;
    return null;
  }

  /* --- Utility Methods --- */

  /** 
   * Returns the default value for a given type (0, false, ""). 
   */
  /*
   * CHECKLIST:
   * When implementing a new variable type, ensure you update BOTH 
   * `getDefaultValueForType()` and `coerceToDeclaredType()` 
   * to handle the type properly.
   */
  private Object getDefaultValueForType(String type, ParserRuleContext ctx) {
    return switch (type) {
      case "HP", "AC", "Int" -> 0;
      case "Gold" -> 0.0;
      case "Bool" -> false;
      case "String" -> "";
      default -> throw new DnDLangError("Unknown type: " + type, ctx.getStart().getLine());
    };
  }

  /** 
   * Coerces a value to the declared type, if compatible (e.g. Int -> Gold becomes Double). 
   */
  private Object coerceToDeclaredType(Object value, String declaredType) {
    /* Gold is always Double: convert an Integer to Double */
    if ("Gold".equals(declaredType) && value instanceof Integer i) {
      return i.doubleValue();
    }
    /* HP is an Integer, but it is bounded to 0 if it drops into negatives */
    if ("HP".equals(declaredType)) {
      int intVal;
      if (value instanceof Double d) intVal = (int) d.doubleValue();
      else if (value instanceof Integer i) intVal = i;
      else throw new IllegalArgumentException("Incompatible type for " + declaredType);

      return Math.max(intVal, 0);
    }
    /* AC is an Integer and cannot be negative */
    if ("AC".equals(declaredType)) {
      int intVal;
      if (value instanceof Double d) intVal = (int) d.doubleValue();
      else if (value instanceof Integer i) intVal = i;
      else throw new IllegalArgumentException("Incompatible type for " + declaredType);

      if (intVal < 0)
        throw new IllegalArgumentException(
            declaredType + " cannot be negative (value: " + intVal + ")");
      return intVal;
    }

    /* Int is obviously an Integer: truncate a Double */
    if ("Int".equals(declaredType) && value instanceof Double d) {
      return (int) d.doubleValue();
    }

    /* If no coercion is needed, simply verify type compatibility */
    boolean typeMatch =
        switch (declaredType) {
          case "Int", "HP", "AC" -> value instanceof Integer;
          case "Float", "Gold" -> value instanceof Double;
          case "Bool" -> value instanceof Boolean;
          case "String" -> value instanceof String;
          case "Void" -> value == null;
          default -> false;
        };
    if (!typeMatch) {

      throw new IllegalArgumentException(
          "Incompatible type: expected "
              + declaredType
              + ", received "
              + value.getClass().getSimpleName());
    }

    return value;
  }

  /** 
   * Executes a declarative block (hero/foe) without creating a new scope. 
   */
  private Object visitDeclarativeBlock(DnDLangParser.BlockContext ctx) {
    if (ctx.statement() != null) {
      for (var stmt : ctx.statement()) {
        visit(stmt);
        if (isBreaking) {
          throw new DnDLangError("'break' used outside of a loop", stmt.getStart().getLine());
        }
      }
    }
    return null;
  }

  /** 
   * Converts a numeric value to double, throwing an error if not numeric. 
   */
  private double asDouble(Object value, ParserRuleContext ctx) {
    if (value instanceof Number num) {
      return num.doubleValue();
    }
    throw new DnDLangError(
        "Math operation on a non-numeric type: " + value, ctx.getStart().getLine());
  }

  /** 
   * Verifies if both operands are integers. 
   */
  private boolean areBothIntegers(Object left, Object right) {
    return left instanceof Integer && right instanceof Integer;
  }

  /** 
   * Generates a random number between 1 and the number of faces of the die. 
   */
  private int rollDice(int sides) {
    return new java.util.Random().nextInt(sides) + 1;
  }

  /** 
   * Resolves an identifier, applying the struct prefix (hero./foe.) if present. 
   */
  private String resolveId(String rawId, int line) {
    /* 
     * Inside hero/foe blocks, we first attempt to resolve with the 
     * structural prefix (e.g. 'hero.hp'). 
     */
    if (!currentStructPrefix.isEmpty()) {
      String prefixedId = currentStructPrefix + rawId;
      if (env.contains(prefixedId)) {
        return prefixedId;
      }
    }

    /* If not found with the prefix, look for the global identifier */
    if (env.contains(rawId)) {
      return rawId;
    }

    throw new DnDLangError("Undeclared variable '" + rawId + "'", line);
  }
}
